# Generated by Django 3.2.4 on 2021-06-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField()),
                ('autore', models.TextField()),
                ('contenuto_testo', models.TextField()),
                ('contenuto_img', models.ImageField(upload_to='')),
                ('tipo_messaggio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Album1',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Nomi',
        ),
    ]
