# Generated by Django 3.2.4 on 2021-06-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210624_2122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tile',
            table='Tile',
        ),
    ]
