# Generated by Django 3.2.4 on 2021-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_column_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='contenuto_img',
            field=models.FileField(upload_to=''),
        ),
    ]
