# Generated by Django 3.2.4 on 2021-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_saveimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveimage',
            name='image',
            field=models.ImageField(upload_to='projects/static/'),
        ),
    ]
